databases: []

services:
  - type: web
    name: prop-intel
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"